name: Deploy WordPress to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 5: SSH into EC2 and deploy the containers
      - name: SSH and deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/app   # Change to your WordPress app's directory
            docker-compose down    # Stop the running containers (if any)
            git pull origin main   # Pull the latest changes from GitHub
            docker-compose up -d   # Start the new containers
